name: Deploy to IONOS (pnpm-10 + SFTP)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 – Code auschecken
      - uses: actions/checkout@v4

      # 2 – pnpm 10.10.0 installieren
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false   

      # 3 – Node + pnpm-Cache aktivieren
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 4 – Dependencies aus Lockfile
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5 – Statischen Build erzeugen
      - name: Build static site
        run: pnpm run build

      # 6 – Deploy via SFTP/SSH
      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port:     ${{ secrets.SERVER_PORT }}
          source:   "out/*"
          target:   ${{ secrets.TARGET_DIR }}
          strip_components: 1
